source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Quoter' do

pod 'Alamofire', '~> 3.0'
pod 'MMDrawerController', '~> 0.5.7'
pod 'Font-Awesome-Swift', '~> 1.4.3'

end

